btosgPlane Class Reference
Infinite plane.
#include <btosg.h>
Public Member Functions
btosgPlane ()
btosgPlane (btosgVec3 v)
btosgPlane (float dx, float dy, float dz)
void createRigidBody ()
void setName (char const *n)
void setMass (double m)
btosgVec3 getPosition ()
btosgQuat getRotation ()
btosgVec3 getEuler ()
void setPosition (const btosgVec3 &p)
void setPosition (float x, float y, float z)
void setRotation (btosgQuat q)
void setRotation (float x, float y, float z, float w)
void setTexture (char const *fname)
void setMaterial (osg::ref_ptr< osg::Material > mat)
void logPosition ()
virtual void update ()
void reset ()
void setInitState ()
void setInitState (btTransform iState)
void loadObjectModel (char const *fname)
Public Attributes
osg::ref_ptr< osg::PositionAttitudeTransform > model
Object's graphical model.
char * name
Object name.
btTransform init_state
Inital state. Applied on reset events.
btRigidBody * body
object's rigid body
btCollisionShape * shape
Object's collision shape.
float mass
Mass of object.
Detailed Description
Infinite plane.
Constructor & Destructor Documentation
btosgPlane() [1/3]
btosgPlane::btosgPlane () [inline]
Constructs a physical infinite plane, viewable as low thickness finite box. Viewable box has dimensions 10,10,0. Plane is created facing Z axis.
btosgPlane() [2/3]
btosgPlane::btosgPlane (btosgVec3 v) [inline]
Constructs a physical infinite plane, viewable as low thickness finite box. Viewable box has dimensions v.x,v.y,v.z. Minimum dimension selects physical plane orientatiton. Plane is created as axis oriented.
btosgPlane() [3/3]
btosgPlane::btosgPlane (float dx, float dy, float dz) [inline]
Constructs a physical infinite plane, viewable as low thickness finite box. Viewable box has dimensions dx,dy,dz. Minimum dimension selects physical plane orientatiton. Plane is created as axis oriented.
Member Function Documentation
createRigidBody()
void btosgPlane::createRigidBody () [inline]
Creates a Rigid Body
getEuler()
btosgVec3 btosgObject::getEuler () [inline], [inherited]
Returns object's attitude as HPR Euler angles.
References btosgQuat::toEuler().
getPosition()
btosgVec3 btosgObject::getPosition () [inline], [inherited]
Returns object's position.
References btosgVec3::btosgVec3().
getRotation()
btosgQuat btosgObject::getRotation () [inline], [inherited]
Returns object's attitude as a Quaternion.
loadObjectModel()
void btosgObject::loadObjectModel (char const * fname) [inherited]
Loads an object model from a Wavefront OBJ file. Loadded model is used to define both the collision and graphical shapes.
logPosition()
void btosgObject::logPosition () [inline], [inherited]
Outputs object's position.
reset()
void btosgObject::reset () [inline], [inherited]
Reposition object to its inital state.
References btosgVec3::btosgVec3().
Referenced by btosgWorld::reset().
setInitState() [1/2]
void btosgObject::setInitState () [inline], [inherited]
Stores current state as init state. Init state is aplied by reset()
Referenced by btosgWorld::stepSimulation().
setInitState() [2/2]
void btosgObject::setInitState (btTransform iState) [inline], [inherited]
Stores iState as init state. Init state is aplied by reset()
setMass()
void btosgObject::setMass (double m) [inline], [inherited]
Sets the object's mass.
Referenced by btosgVehicle::btosgVehicle().
setMaterial()
void btosgObject::setMaterial (osg::ref_ptr< osg::Material > mat) [inline], [inherited]
Sets the material properties for the object.
Referenced by btosgVehicle::btosgVehicle().
setName()
void btosgObject::setName (char const * n) [inline], [inherited]
Sets the object's name.
setPosition() [1/2]
void btosgObject::setPosition (const btosgVec3 & p) [inline], [inherited]
Sets objects position.
setPosition() [2/2]
void btosgObject::setPosition (float x, float y, float z) [inline], [inherited]
Sets objects position.
References btosgVec3::btosgVec3().
setRotation() [1/2]
void btosgObject::setRotation (btosgQuat q) [inline], [inherited]
Sets objects attitude from a quaternion.
setRotation() [2/2]
void btosgObject::setRotation (float x, float y, float z, float w) [inline], [inherited]
Sets objects attitude from the quaternion coords.
setTexture()
void btosgObject::setTexture (char const * fname) [inherited]
Sets the object texture from a loaded image file.
update()
virtual void btosgObject::update () [inline], [virtual], [inherited]
Objects's update callback. This function is called automatically from World::setpSimulation() for each registered object. Positions graphical object from its physhical state.
Reimplemented in btosgVehicle.
References btosgVec3::btosgVec3().
Referenced by btosgWorld::stepSimulation(), and btosgVehicle::update().
Member Data Documentation
body
btRigidBody* btosgObject::body [inherited]
object's rigid body
Referenced by btosgWorld::addObject(), btosgVehicle::btosgVehicle(), btosgVehicle::logPosition(), and btosgVehicle::printInfo().
init_state
btTransform btosgObject::init_state [inherited]
Inital state. Applied on reset events.
mass
float btosgObject::mass [inherited]
Mass of object.
Referenced by btosgVehicle::printInfo().
model
osg::ref_ptr<osg::PositionAttitudeTransform> btosgObject::model [inherited]
Object's graphical model.
Referenced by btosgWorld::addObject(), btosgVehicle::addWheels(), and btosgVehicle::btosgVehicle().
name
char* btosgObject::name [inherited]
Object name.
Referenced by btosgVehicle::logPosition().
shape
btCollisionShape* btosgObject::shape [inherited]
Object's collision shape.
Referenced by btosgVehicle::btosgVehicle().
The documentation for this class was generated from the following file:
btosg.h (/*
 *	btosg.h
 *
 *	(c) Miguel Leitao, 2016
 *
 */
#ifndef BTOSG_H
#define BTOSG_H 1
#define YES 1
#define NO 0
#include <osgDB/ReadFile>
#include <osg/MatrixTransform>
#include <osg/PositionAttitudeTransform>
#include <osgGA/TrackballManipulator>
#include <osg/ShapeDrawable>
#include <osg/Plane>
#include <osg/LightSource>
#include <osg/Material>
#include <btBulletDynamicsCommon.h>
#if BTOSG_LOAD_OBJ==YES
#include `loadOBJ/include/LoadMeshFromOb
#include `loadOBJ/include/GLInstanceGrap
//include <GLInstanceGraphicsShape.h>
#endif
//include <GLInstanceGraphicsShape.h>
#ifdef BTOSG_SHADOW
#include <osgShadow/ShadowedScene>
#include <osgShadow/ShadowMap>
#endif
#include <forward_list>
/* Direct update of positions and orient
 * or normal objects that are syncronize
 * Direct update can be enabled to allow
 * update the graphics model directly.
 * This can be used in special cases lik
 * btosgWorld or Worlds that are not ste
 */
#define AVOID_DIRECT_MODEL_UPDATE
#define max(a,b) \
   ({ __typeof__ (a))