btosgWorld Class Reference
Physical and visual world.
#include <btosg.h>
Public Member Functions
void stepSimulation (btScalar timeStep, int maxSubSteps)
void addObject (class btosgObject *obj)
void reset ()
Public Attributes
btDynamicsWorld * dynamic
osg::ref_ptr< osg::Group > scene
Pointer to osg::Group object storing the root node of the object tree.
std::forward_list< class btosgObject * > objects
List of Objects.
Detailed Description
Physical and visual world.
Integrates a btDynamicsWorld and an osg::Group. Provides automated updating of graphical objects from related physical simulated bodies.
Member Function Documentation
addObject()
void btosgWorld::addObject (class btosgObject * obj)
Registers the object obj into a simulation world.
References btosgObject::body, and btosgObject::model.
reset()
void btosgWorld::reset ()
Reset all registered objects.
References btosgObject::reset().
stepSimulation()
void btosgWorld::stepSimulation (btScalar timeStep, int maxSubSteps)
Performs a simulation step.
References btosgObject::setInitState(), and btosgObject::update().
Member Data Documentation
dynamic
btDynamicsWorld* btosgWorld::dynamic
Pointer to btDynamicsWorld object.
Referenced by btosgVehicle::btosgVehicle().
objects
std::forward_list<class btosgObject*> btosgWorld::objects
List of Objects.
scene
osg::ref_ptr<osg::Group> btosgWorld::scene
Pointer to osg::Group object storing the root node of the object tree.
The documentation for this class was generated from the following files:
btosg.h (/*
 *	btosg.h
 *
 *	(c) Miguel Leitao, 2016
 *
 */
#ifndef BTOSG_H
#define BTOSG_H 1
#define YES 1
#define NO 0
#include <osgDB/ReadFile>
#include <osg/MatrixTransform>
#include <osg/PositionAttitudeTransform>
#include <osgGA/TrackballManipulator>
#include <osg/ShapeDrawable>
#include <osg/Plane>
#include <osg/LightSource>
#include <osg/Material>
#include <btBulletDynamicsCommon.h>
#if BTOSG_LOAD_OBJ==YES
#include `loadOBJ/include/LoadMeshFromOb
#include `loadOBJ/include/GLInstanceGrap
//include <GLInstanceGraphicsShape.h>
#endif
//include <GLInstanceGraphicsShape.h>
#ifdef BTOSG_SHADOW
#include <osgShadow/ShadowedScene>
#include <osgShadow/ShadowMap>
#endif
#include <forward_list>
/* Direct update of positions and orient
 * or normal objects that are syncronize
 * Direct update can be enabled to allow
 * update the graphics model directly.
 * This can be used in special cases lik
 * btosgWorld or Worlds that are not ste
 */
#define AVOID_DIRECT_MODEL_UPDATE
#define max(a,b) \
   ({ __typeof__ (a))
btosg.cpp (/*
	btosg.cpp
	Miguel Leitao, 2016
*/
#include `btosg.h`
#include <osg/Material>
#include <osg/Texture2D>
#define _DEBUG_ (0)
btVector3 quat2Euler(const btQuaternion&
{
    // Implementation not tested.
    // roll (x-axis rotation)
    double sinr = +2.0 * (q.w() * q.x()
    double cosr = +1.0 - 2.0 * (q.x() *
    double roll = atan2(sinr, cosr);
    // pitch (y-axis rotation)
    double sinp = +2.0 * (q.w() * q.y()
    double pitch;
    if (fabs(sinp) >= 1)
        pitch = copysign(M_PI / 2, sinp)
    else
        pitch = asin(sinp);
    // yaw (z-axis rotation)
    double siny = +2.0 * (q.w() * q.z()
    double cosy = +1.0 - 2.0 * (q.y() *
    double yaw = atan2(siny, cosy);
    return btVector3(yaw,pitch,roll);
}
btosgVec3 btosgQuat::toEuler()
{
    return quat2Euler(*this);
}
btosgWorld::~btosgWorld() {
    delete dynamic; // ????
    delete solver;
    delete dispatcher;
    delete collisionConfiguration;
    delete broadphase;
    for (auto it = objects.begin(); it
        btosgObject)